sudo: required
dist: xenial
language: csharp
solution: AnyPackageManagerCache.sln
dotnet: 2.2.300
script:
 - ls
 - dotnet restore
 - dotnet publish -c Release /p:PublishProfile="AnyPackageManagerCache\Properties\PublishProfiles\FolderProfile.pubxml"